# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
                            QSize, Qt)
from PySide6.QtGui import (QAction, QCursor, QFont, QIcon)
from PySide6.QtWidgets import (
    QCheckBox, QDial, QDockWidget,
    QFormLayout, QFrame, QGridLayout, QHBoxLayout,
    QLayout, QMainWindow, QPlainTextEdit, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QTabWidget,
    QTextEdit, QToolButton, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.ApplicationModal)
        MainWindow.resize(1920, 1080)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(700, 700))
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        MainWindow.setBaseSize(QSize(600, 600))
        font = QFont()
        font.setPointSize(12)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.action_Quit = QAction(MainWindow)
        self.action_Quit.setObjectName(u"action_Quit")
        self.main_widget = QWidget(MainWindow)
        self.main_widget.setObjectName(u"main_widget")
        self.main_widget.setEnabled(True)
        self.main_widget.setMinimumSize(QSize(650, 650))
        self.main_widget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.main_widget.setAutoFillBackground(False)
        self.main_widget.setStyleSheet(u"")
        self.main_layout = QGridLayout(self.main_widget)
        self.main_layout.setObjectName(u"main_layout")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.plug_button = QPushButton(self.main_widget)
        self.plug_button.setObjectName(u"plug_button")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.plug_button.sizePolicy().hasHeightForWidth())
        self.plug_button.setSizePolicy(sizePolicy1)
        self.plug_button.setMinimumSize(QSize(24, 24))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(True)
        font1.setKerning(True)
        self.plug_button.setFont(font1)
        self.plug_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.plug_button.setCheckable(False)
        self.plug_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.plug_button)


        self.main_layout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)

        self.horizontalLayout_1 = QHBoxLayout()
        self.horizontalLayout_1.setObjectName(u"horizontalLayout_1")
        self.about_button = QPushButton(self.main_widget)
        self.about_button.setObjectName(u"about_button")
        sizePolicy1.setHeightForWidth(self.about_button.sizePolicy().hasHeightForWidth())
        self.about_button.setSizePolicy(sizePolicy1)
        self.about_button.setMinimumSize(QSize(24, 24))
        self.about_button.setFont(font1)
        self.about_button.setCursor(QCursor(Qt.WhatsThisCursor))
        self.about_button.setCheckable(False)
        self.about_button.setFlat(True)

        self.horizontalLayout_1.addWidget(self.about_button)


        self.main_layout.addLayout(self.horizontalLayout_1, 1, 2, 1, 1)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.conf_button = QPushButton(self.main_widget)
        self.conf_button.setObjectName(u"conf_button")
        sizePolicy1.setHeightForWidth(self.conf_button.sizePolicy().hasHeightForWidth())
        self.conf_button.setSizePolicy(sizePolicy1)
        self.conf_button.setMinimumSize(QSize(24, 24))
        self.conf_button.setFont(font1)
        self.conf_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.conf_button.setCheckable(False)
        self.conf_button.setFlat(True)

        self.horizontalLayout_4.addWidget(self.conf_button)


        self.main_layout.addLayout(self.horizontalLayout_4, 3, 4, 1, 1)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.log_button = QPushButton(self.main_widget)
        self.log_button.setObjectName(u"log_button")
        sizePolicy1.setHeightForWidth(self.log_button.sizePolicy().hasHeightForWidth())
        self.log_button.setSizePolicy(sizePolicy1)
        self.log_button.setMinimumSize(QSize(24, 24))
        self.log_button.setFont(font1)
        self.log_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.log_button.setCheckable(False)
        self.log_button.setFlat(True)

        self.horizontalLayout_2.addWidget(self.log_button)


        self.main_layout.addLayout(self.horizontalLayout_2, 5, 2, 1, 1)

        self.shuttle_tab = QTabWidget(self.main_widget)
        self.shuttle_tab.setObjectName(u"shuttle_tab")
        self.shuttle_tab.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.shuttle_tab.sizePolicy().hasHeightForWidth())
        self.shuttle_tab.setSizePolicy(sizePolicy1)
        self.shuttle_tab.setMinimumSize(QSize(350, 750))
        self.shuttle_tab.setMaximumSize(QSize(350, 750))
        self.shuttle_tab.setAutoFillBackground(False)
        self.shuttle_tab.setStyleSheet(u"")
        self.shuttle_widget = QWidget()
        self.shuttle_widget.setObjectName(u"shuttle_widget")
        sizePolicy1.setHeightForWidth(self.shuttle_widget.sizePolicy().hasHeightForWidth())
        self.shuttle_widget.setSizePolicy(sizePolicy1)
        self.shuttle_widget.setMinimumSize(QSize(350, 750))
        self.shuttle_widget.setMaximumSize(QSize(350, 750))
        self.shuttle_widget.setStyleSheet(u"QWidget#shuttle_widget {background:\n"
"         url(images/Xpress.png);\n"
"        background-repeat:no-repeat;}\n"
"       ")
        self.button_1 = QCheckBox(self.shuttle_widget)
        self.button_1.setObjectName(u"button_1")
        self.button_1.setGeometry(QRect(20, 270, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy1)
        self.button_1.setMinimumSize(QSize(24, 24))
        self.button_1.setFont(font)
        self.button_1.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.usb_status = QPushButton(self.shuttle_widget)
        self.usb_status.setObjectName(u"usb_status")
        self.usb_status.setEnabled(False)
        self.usb_status.setGeometry(QRect(163, 10, 24, 24))
        sizePolicy1.setHeightForWidth(self.usb_status.sizePolicy().hasHeightForWidth())
        self.usb_status.setSizePolicy(sizePolicy1)
        self.usb_status.setMinimumSize(QSize(24, 24))
        self.usb_status.setFont(font1)
        self.usb_status.setCursor(QCursor(Qt.ArrowCursor))
        self.usb_status.setAutoFillBackground(False)
        self.usb_status.setText(u"")
        icon = QIcon()
        icon.addFile(u"images/usb_black_24.png", QSize(), QIcon.Disabled, QIcon.Off)
        icon.addFile(u"images/usb_white_24.png", QSize(), QIcon.Disabled, QIcon.On)
        self.usb_status.setIcon(icon)
        self.usb_status.setIconSize(QSize(24, 24))
        self.usb_status.setCheckable(True)
        self.usb_status.setChecked(False)
        self.usb_status.setFlat(True)
        self.button_5 = QCheckBox(self.shuttle_widget)
        self.button_5.setObjectName(u"button_5")
        self.button_5.setGeometry(QRect(305, 270, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_5.sizePolicy().hasHeightForWidth())
        self.button_5.setSizePolicy(sizePolicy1)
        self.button_5.setMinimumSize(QSize(24, 24))
        self.button_5.setFont(font)
        self.button_5.setLayoutDirection(Qt.RightToLeft)
        self.button_5.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_pos4 = QRadioButton(self.shuttle_widget)
        self.wheel_pos4.setObjectName(u"wheel_pos4")
        self.wheel_pos4.setGeometry(QRect(235, 213, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos4.sizePolicy().hasHeightForWidth())
        self.wheel_pos4.setSizePolicy(sizePolicy1)
        self.wheel_pos4.setMinimumSize(QSize(24, 24))
        self.wheel_pos4.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_cent0 = QRadioButton(self.shuttle_widget)
        self.wheel_cent0.setObjectName(u"wheel_cent0")
        self.wheel_cent0.setGeometry(QRect(163, 176, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_cent0.sizePolicy().hasHeightForWidth())
        self.wheel_cent0.setSizePolicy(sizePolicy1)
        self.wheel_cent0.setMinimumSize(QSize(24, 24))
        self.wheel_cent0.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_cent0.setChecked(True)
        self.wheel_pos1 = QRadioButton(self.shuttle_widget)
        self.wheel_pos1.setObjectName(u"wheel_pos1")
        self.wheel_pos1.setGeometry(QRect(181, 179, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos1.sizePolicy().hasHeightForWidth())
        self.wheel_pos1.setSizePolicy(sizePolicy1)
        self.wheel_pos1.setMinimumSize(QSize(24, 24))
        self.wheel_pos1.setStyleSheet(u"color: white;")
        self.wheel_pos2 = QRadioButton(self.shuttle_widget)
        self.wheel_pos2.setObjectName(u"wheel_pos2")
        self.wheel_pos2.setGeometry(QRect(200, 186, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos2.sizePolicy().hasHeightForWidth())
        self.wheel_pos2.setSizePolicy(sizePolicy1)
        self.wheel_pos2.setMinimumSize(QSize(24, 24))
        self.wheel_pos2.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.dial = QDial(self.shuttle_widget)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(115, 226, 120, 120))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.dial.sizePolicy().hasHeightForWidth())
        self.dial.setSizePolicy(sizePolicy2)
        self.dial.setMinimumSize(QSize(24, 24))
        self.dial.setAutoFillBackground(False)
        self.dial.setStyleSheet(u"background-color: black;")
        self.dial.setMinimum(0)
        self.dial.setMaximum(10)
        self.dial.setPageStep(1)
        self.dial.setValue(5)
        self.dial.setSliderPosition(5)
        self.dial.setInvertedAppearance(False)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(True)
        self.dial.setNotchTarget(3.700000000000000)
        self.dial.setNotchesVisible(False)
        self.wheel_neg6 = QRadioButton(self.shuttle_widget)
        self.wheel_neg6.setObjectName(u"wheel_neg6")
        self.wheel_neg6.setGeometry(QRect(67, 250, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg6.sizePolicy().hasHeightForWidth())
        self.wheel_neg6.setSizePolicy(sizePolicy1)
        self.wheel_neg6.setMinimumSize(QSize(24, 24))
        self.wheel_neg6.setStyleSheet(u"color: white;")
        self.wheel_pos5 = QRadioButton(self.shuttle_widget)
        self.wheel_pos5.setObjectName(u"wheel_pos5")
        self.wheel_pos5.setGeometry(QRect(248, 232, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos5.sizePolicy().hasHeightForWidth())
        self.wheel_pos5.setSizePolicy(sizePolicy1)
        self.wheel_pos5.setMinimumSize(QSize(24, 24))
        self.wheel_pos5.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.button_2 = QCheckBox(self.shuttle_widget)
        self.button_2.setObjectName(u"button_2")
        self.button_2.setGeometry(QRect(65, 173, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_2.sizePolicy().hasHeightForWidth())
        self.button_2.setSizePolicy(sizePolicy1)
        self.button_2.setMinimumSize(QSize(24, 24))
        self.button_2.setFont(font)
        self.button_2.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_neg5 = QRadioButton(self.shuttle_widget)
        self.wheel_neg5.setObjectName(u"wheel_neg5")
        self.wheel_neg5.setGeometry(QRect(75, 228, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg5.sizePolicy().hasHeightForWidth())
        self.wheel_neg5.setSizePolicy(sizePolicy1)
        self.wheel_neg5.setMinimumSize(QSize(24, 24))
        self.wheel_neg5.setStyleSheet(u"color: white;")
        self.wheel_pos6 = QRadioButton(self.shuttle_widget)
        self.wheel_pos6.setObjectName(u"wheel_pos6")
        self.wheel_pos6.setGeometry(QRect(256, 253, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos6.sizePolicy().hasHeightForWidth())
        self.wheel_pos6.setSizePolicy(sizePolicy1)
        self.wheel_pos6.setMinimumSize(QSize(24, 24))
        self.wheel_pos6.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_neg1 = QRadioButton(self.shuttle_widget)
        self.wheel_neg1.setObjectName(u"wheel_neg1")
        self.wheel_neg1.setGeometry(QRect(142, 179, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg1.sizePolicy().hasHeightForWidth())
        self.wheel_neg1.setSizePolicy(sizePolicy1)
        self.wheel_neg1.setMinimumSize(QSize(24, 24))
        self.wheel_neg1.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.button_4 = QCheckBox(self.shuttle_widget)
        self.button_4.setObjectName(u"button_4")
        self.button_4.setGeometry(QRect(260, 173, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_4.sizePolicy().hasHeightForWidth())
        self.button_4.setSizePolicy(sizePolicy1)
        self.button_4.setMinimumSize(QSize(24, 24))
        self.button_4.setFont(font)
        self.button_4.setLayoutDirection(Qt.RightToLeft)
        self.button_4.setAutoFillBackground(False)
        self.button_4.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_pos7 = QRadioButton(self.shuttle_widget)
        self.wheel_pos7.setObjectName(u"wheel_pos7")
        self.wheel_pos7.setGeometry(QRect(260, 275, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos7.sizePolicy().hasHeightForWidth())
        self.wheel_pos7.setSizePolicy(sizePolicy1)
        self.wheel_pos7.setMinimumSize(QSize(24, 24))
        self.wheel_pos7.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.button_3 = QCheckBox(self.shuttle_widget)
        self.button_3.setObjectName(u"button_3")
        self.button_3.setGeometry(QRect(163, 135, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_3.sizePolicy().hasHeightForWidth())
        self.button_3.setSizePolicy(sizePolicy1)
        self.button_3.setMinimumSize(QSize(24, 24))
        self.button_3.setFont(font)
        self.button_3.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.button_3.setTristate(False)
        self.wheel_neg2 = QRadioButton(self.shuttle_widget)
        self.wheel_neg2.setObjectName(u"wheel_neg2")
        self.wheel_neg2.setGeometry(QRect(123, 185, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg2.sizePolicy().hasHeightForWidth())
        self.wheel_neg2.setSizePolicy(sizePolicy1)
        self.wheel_neg2.setMinimumSize(QSize(24, 24))
        self.wheel_neg2.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_pos3 = QRadioButton(self.shuttle_widget)
        self.wheel_pos3.setObjectName(u"wheel_pos3")
        self.wheel_pos3.setGeometry(QRect(218, 197, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos3.sizePolicy().hasHeightForWidth())
        self.wheel_pos3.setSizePolicy(sizePolicy1)
        self.wheel_pos3.setMinimumSize(QSize(24, 24))
        self.wheel_pos3.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_neg3 = QRadioButton(self.shuttle_widget)
        self.wheel_neg3.setObjectName(u"wheel_neg3")
        self.wheel_neg3.setGeometry(QRect(105, 195, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg3.sizePolicy().hasHeightForWidth())
        self.wheel_neg3.setSizePolicy(sizePolicy1)
        self.wheel_neg3.setMinimumSize(QSize(24, 24))
        self.wheel_neg3.setStyleSheet(u"color: white;")
        self.wheel_neg4 = QRadioButton(self.shuttle_widget)
        self.wheel_neg4.setObjectName(u"wheel_neg4")
        self.wheel_neg4.setGeometry(QRect(88, 210, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg4.sizePolicy().hasHeightForWidth())
        self.wheel_neg4.setSizePolicy(sizePolicy1)
        self.wheel_neg4.setMinimumSize(QSize(24, 24))
        self.wheel_neg4.setStyleSheet(u"background: #000000ff;\n"
"         color: white;\n"
"        ")
        self.wheel_neg7 = QRadioButton(self.shuttle_widget)
        self.wheel_neg7.setObjectName(u"wheel_neg7")
        self.wheel_neg7.setGeometry(QRect(63, 275, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg7.sizePolicy().hasHeightForWidth())
        self.wheel_neg7.setSizePolicy(sizePolicy1)
        self.wheel_neg7.setMinimumSize(QSize(24, 24))
        self.wheel_neg7.setStyleSheet(u"color: white;")
        self.shuttle_tab.addTab(self.shuttle_widget, "")
        self.dial.raise_()
        self.button_1.raise_()
        self.usb_status.raise_()
        self.button_5.raise_()
        self.wheel_pos4.raise_()
        self.wheel_cent0.raise_()
        self.wheel_pos1.raise_()
        self.wheel_pos2.raise_()
        self.wheel_neg6.raise_()
        self.wheel_pos5.raise_()
        self.button_2.raise_()
        self.wheel_neg5.raise_()
        self.wheel_pos6.raise_()
        self.wheel_neg1.raise_()
        self.button_4.raise_()
        self.wheel_pos7.raise_()
        self.button_3.raise_()
        self.wheel_neg2.raise_()
        self.wheel_pos3.raise_()
        self.wheel_neg3.raise_()
        self.wheel_neg4.raise_()
        self.wheel_neg7.raise_()
        self.shuttlepro_widget = QWidget()
        self.shuttlepro_widget.setObjectName(u"shuttlepro_widget")
        self.shuttlepro_widget.setStyleSheet(u"QWidget#shuttlepro_widget {background:\n"
"         url(images/PRO.png);\n"
"         background-repeat:no-repeat;}\n"
"        ")
        self.shuttle_tab.addTab(self.shuttlepro_widget, "")
        self.shuttleprov2_widget = QWidget()
        self.shuttleprov2_widget.setObjectName(u"shuttleprov2_widget")
        sizePolicy1.setHeightForWidth(self.shuttleprov2_widget.sizePolicy().hasHeightForWidth())
        self.shuttleprov2_widget.setSizePolicy(sizePolicy1)
        self.shuttleprov2_widget.setMinimumSize(QSize(350, 750))
        self.shuttleprov2_widget.setMaximumSize(QSize(350, 750))
        self.shuttleprov2_widget.setStyleSheet(u"QWidget#shuttleprov2_widget {background:\n"
"         url(images/PROv2.png);\n"
"         background-repeat:no-repeat;}\n"
"        ")
        self.wheel_neg4_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_neg4_2.setObjectName(u"wheel_neg4_2")
        self.wheel_neg4_2.setGeometry(QRect(88, 210, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg4_2.sizePolicy().hasHeightForWidth())
        self.wheel_neg4_2.setSizePolicy(sizePolicy1)
        self.wheel_neg4_2.setMinimumSize(QSize(24, 24))
        self.wheel_neg4_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_neg7_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_neg7_2.setObjectName(u"wheel_neg7_2")
        self.wheel_neg7_2.setGeometry(QRect(63, 275, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg7_2.sizePolicy().hasHeightForWidth())
        self.wheel_neg7_2.setSizePolicy(sizePolicy1)
        self.wheel_neg7_2.setMinimumSize(QSize(24, 24))
        self.wheel_neg7_2.setStyleSheet(u"color: white;")
        self.usb_status_2 = QPushButton(self.shuttleprov2_widget)
        self.usb_status_2.setObjectName(u"usb_status_2")
        self.usb_status_2.setEnabled(False)
        self.usb_status_2.setGeometry(QRect(163, 10, 24, 24))
        sizePolicy1.setHeightForWidth(self.usb_status_2.sizePolicy().hasHeightForWidth())
        self.usb_status_2.setSizePolicy(sizePolicy1)
        self.usb_status_2.setMinimumSize(QSize(24, 24))
        self.usb_status_2.setFont(font1)
        self.usb_status_2.setCursor(QCursor(Qt.ArrowCursor))
        self.usb_status_2.setAutoFillBackground(False)
        self.usb_status_2.setText(u"")
        self.usb_status_2.setIcon(icon)
        self.usb_status_2.setIconSize(QSize(24, 24))
        self.usb_status_2.setCheckable(True)
        self.usb_status_2.setChecked(False)
        self.usb_status_2.setFlat(True)
        self.wheel_neg2_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_neg2_2.setObjectName(u"wheel_neg2_2")
        self.wheel_neg2_2.setGeometry(QRect(123, 185, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg2_2.sizePolicy().hasHeightForWidth())
        self.wheel_neg2_2.setSizePolicy(sizePolicy1)
        self.wheel_neg2_2.setMinimumSize(QSize(24, 24))
        self.wheel_neg2_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.button_6 = QCheckBox(self.shuttleprov2_widget)
        self.button_6.setObjectName(u"button_6")
        self.button_6.setGeometry(QRect(65, 173, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_6.sizePolicy().hasHeightForWidth())
        self.button_6.setSizePolicy(sizePolicy1)
        self.button_6.setMinimumSize(QSize(24, 24))
        self.button_6.setFont(font)
        self.button_6.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_neg5_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_neg5_2.setObjectName(u"wheel_neg5_2")
        self.wheel_neg5_2.setGeometry(QRect(75, 228, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg5_2.sizePolicy().hasHeightForWidth())
        self.wheel_neg5_2.setSizePolicy(sizePolicy1)
        self.wheel_neg5_2.setMinimumSize(QSize(24, 24))
        self.wheel_neg5_2.setStyleSheet(u"color: white;")
        self.button_7 = QCheckBox(self.shuttleprov2_widget)
        self.button_7.setObjectName(u"button_7")
        self.button_7.setGeometry(QRect(163, 135, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_7.sizePolicy().hasHeightForWidth())
        self.button_7.setSizePolicy(sizePolicy1)
        self.button_7.setMinimumSize(QSize(24, 24))
        self.button_7.setFont(font)
        self.button_7.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.button_7.setTristate(False)
        self.wheel_pos5_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_pos5_2.setObjectName(u"wheel_pos5_2")
        self.wheel_pos5_2.setGeometry(QRect(248, 232, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos5_2.sizePolicy().hasHeightForWidth())
        self.wheel_pos5_2.setSizePolicy(sizePolicy1)
        self.wheel_pos5_2.setMinimumSize(QSize(24, 24))
        self.wheel_pos5_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_pos3_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_pos3_2.setObjectName(u"wheel_pos3_2")
        self.wheel_pos3_2.setGeometry(QRect(218, 197, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos3_2.sizePolicy().hasHeightForWidth())
        self.wheel_pos3_2.setSizePolicy(sizePolicy1)
        self.wheel_pos3_2.setMinimumSize(QSize(24, 24))
        self.wheel_pos3_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_neg6_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_neg6_2.setObjectName(u"wheel_neg6_2")
        self.wheel_neg6_2.setGeometry(QRect(67, 250, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg6_2.sizePolicy().hasHeightForWidth())
        self.wheel_neg6_2.setSizePolicy(sizePolicy1)
        self.wheel_neg6_2.setMinimumSize(QSize(24, 24))
        self.wheel_neg6_2.setStyleSheet(u"color: white;")
        self.wheel_pos1_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_pos1_2.setObjectName(u"wheel_pos1_2")
        self.wheel_pos1_2.setGeometry(QRect(181, 179, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos1_2.sizePolicy().hasHeightForWidth())
        self.wheel_pos1_2.setSizePolicy(sizePolicy1)
        self.wheel_pos1_2.setMinimumSize(QSize(24, 24))
        self.wheel_pos1_2.setStyleSheet(u"color: white;")
        self.wheel_cent0_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_cent0_2.setObjectName(u"wheel_cent0_2")
        self.wheel_cent0_2.setGeometry(QRect(163, 176, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_cent0_2.sizePolicy().hasHeightForWidth())
        self.wheel_cent0_2.setSizePolicy(sizePolicy1)
        self.wheel_cent0_2.setMinimumSize(QSize(24, 24))
        self.wheel_cent0_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_cent0_2.setChecked(True)
        self.wheel_pos2_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_pos2_2.setObjectName(u"wheel_pos2_2")
        self.wheel_pos2_2.setGeometry(QRect(200, 186, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos2_2.sizePolicy().hasHeightForWidth())
        self.wheel_pos2_2.setSizePolicy(sizePolicy1)
        self.wheel_pos2_2.setMinimumSize(QSize(24, 24))
        self.wheel_pos2_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_pos4_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_pos4_2.setObjectName(u"wheel_pos4_2")
        self.wheel_pos4_2.setGeometry(QRect(235, 213, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos4_2.sizePolicy().hasHeightForWidth())
        self.wheel_pos4_2.setSizePolicy(sizePolicy1)
        self.wheel_pos4_2.setMinimumSize(QSize(24, 24))
        self.wheel_pos4_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.button_8 = QCheckBox(self.shuttleprov2_widget)
        self.button_8.setObjectName(u"button_8")
        self.button_8.setGeometry(QRect(260, 173, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_8.sizePolicy().hasHeightForWidth())
        self.button_8.setSizePolicy(sizePolicy1)
        self.button_8.setMinimumSize(QSize(24, 24))
        self.button_8.setFont(font)
        self.button_8.setLayoutDirection(Qt.RightToLeft)
        self.button_8.setAutoFillBackground(False)
        self.button_8.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_pos6_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_pos6_2.setObjectName(u"wheel_pos6_2")
        self.wheel_pos6_2.setGeometry(QRect(256, 253, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos6_2.sizePolicy().hasHeightForWidth())
        self.wheel_pos6_2.setSizePolicy(sizePolicy1)
        self.wheel_pos6_2.setMinimumSize(QSize(24, 24))
        self.wheel_pos6_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.button_9 = QCheckBox(self.shuttleprov2_widget)
        self.button_9.setObjectName(u"button_9")
        self.button_9.setGeometry(QRect(20, 270, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_9.sizePolicy().hasHeightForWidth())
        self.button_9.setSizePolicy(sizePolicy1)
        self.button_9.setMinimumSize(QSize(24, 24))
        self.button_9.setFont(font)
        self.button_9.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.dial_2 = QDial(self.shuttleprov2_widget)
        self.dial_2.setObjectName(u"dial_2")
        self.dial_2.setGeometry(QRect(115, 226, 120, 120))
        sizePolicy2.setHeightForWidth(self.dial_2.sizePolicy().hasHeightForWidth())
        self.dial_2.setSizePolicy(sizePolicy2)
        self.dial_2.setMinimumSize(QSize(24, 24))
        self.dial_2.setAutoFillBackground(False)
        self.dial_2.setStyleSheet(u"background-color: black;")
        self.dial_2.setMinimum(0)
        self.dial_2.setMaximum(10)
        self.dial_2.setPageStep(1)
        self.dial_2.setValue(5)
        self.dial_2.setSliderPosition(5)
        self.dial_2.setInvertedAppearance(False)
        self.dial_2.setInvertedControls(False)
        self.dial_2.setWrapping(True)
        self.dial_2.setNotchTarget(3.700000000000000)
        self.dial_2.setNotchesVisible(False)
        self.wheel_neg1_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_neg1_2.setObjectName(u"wheel_neg1_2")
        self.wheel_neg1_2.setGeometry(QRect(142, 179, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg1_2.sizePolicy().hasHeightForWidth())
        self.wheel_neg1_2.setSizePolicy(sizePolicy1)
        self.wheel_neg1_2.setMinimumSize(QSize(24, 24))
        self.wheel_neg1_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_pos7_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_pos7_2.setObjectName(u"wheel_pos7_2")
        self.wheel_pos7_2.setGeometry(QRect(260, 275, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_pos7_2.sizePolicy().hasHeightForWidth())
        self.wheel_pos7_2.setSizePolicy(sizePolicy1)
        self.wheel_pos7_2.setMinimumSize(QSize(24, 24))
        self.wheel_pos7_2.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.button_10 = QCheckBox(self.shuttleprov2_widget)
        self.button_10.setObjectName(u"button_10")
        self.button_10.setGeometry(QRect(305, 270, 24, 24))
        sizePolicy1.setHeightForWidth(self.button_10.sizePolicy().hasHeightForWidth())
        self.button_10.setSizePolicy(sizePolicy1)
        self.button_10.setMinimumSize(QSize(24, 24))
        self.button_10.setFont(font)
        self.button_10.setLayoutDirection(Qt.RightToLeft)
        self.button_10.setStyleSheet(u"background: #000000ff;\n"
"          color: white;\n"
"         ")
        self.wheel_neg3_2 = QRadioButton(self.shuttleprov2_widget)
        self.wheel_neg3_2.setObjectName(u"wheel_neg3_2")
        self.wheel_neg3_2.setGeometry(QRect(105, 195, 24, 24))
        sizePolicy1.setHeightForWidth(self.wheel_neg3_2.sizePolicy().hasHeightForWidth())
        self.wheel_neg3_2.setSizePolicy(sizePolicy1)
        self.wheel_neg3_2.setMinimumSize(QSize(24, 24))
        self.wheel_neg3_2.setStyleSheet(u"color: white;")
        self.shuttle_tab.addTab(self.shuttleprov2_widget, "")

        self.main_layout.addWidget(self.shuttle_tab, 3, 2, 1, 1)

        MainWindow.setCentralWidget(self.main_widget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setMinimumSize(QSize(600, 0))
        MainWindow.setStatusBar(self.statusbar)
        self.about_widget = QDockWidget(MainWindow)
        self.about_widget.setObjectName(u"about_widget")
        self.about_widget.setEnabled(True)
        sizePolicy.setHeightForWidth(self.about_widget.sizePolicy().hasHeightForWidth())
        self.about_widget.setSizePolicy(sizePolicy)
        self.about_widget.setMinimumSize(QSize(0, 0))
        self.about_widget.setMaximumSize(QSize(16777215, 16777215))
        self.about_widget.setVisible(True)
        self.about_widget.setFloating(False)
        self.about_widget.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetMovable)
        self.about_widget.setAllowedAreas(Qt.TopDockWidgetArea)
        self.about_layout = QWidget()
        self.about_layout.setObjectName(u"about_layout")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.about_layout.sizePolicy().hasHeightForWidth())
        self.about_layout.setSizePolicy(sizePolicy3)
        self.about_layout.setAutoFillBackground(False)
        self.gridLayout_3 = QGridLayout(self.about_layout)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.about_text = QTextEdit(self.about_layout)
        self.about_text.setObjectName(u"about_text")
        self.about_text.setFocusPolicy(Qt.WheelFocus)
        self.about_text.setAcceptDrops(False)
        self.about_text.setStyleSheet(u"color: white;")
        self.about_text.setFrameShape(QFrame.StyledPanel)
        self.about_text.setFrameShadow(QFrame.Sunken)
        self.about_text.setUndoRedoEnabled(False)
        self.about_text.setReadOnly(True)
        self.about_text.setAcceptRichText(True)

        self.gridLayout_3.addWidget(self.about_text, 0, 0, 1, 1)

        self.about_widget.setWidget(self.about_layout)
        MainWindow.addDockWidget(Qt.TopDockWidgetArea, self.about_widget)
        self.log_widget = QDockWidget(MainWindow)
        self.log_widget.setObjectName(u"log_widget")
        self.log_widget.setEnabled(True)
        sizePolicy.setHeightForWidth(self.log_widget.sizePolicy().hasHeightForWidth())
        self.log_widget.setSizePolicy(sizePolicy)
        self.log_widget.setMinimumSize(QSize(0, 0))
        self.log_widget.setMaximumSize(QSize(16777215, 16777215))
        self.log_widget.setFont(font)
        self.log_widget.setVisible(True)
        self.log_widget.setFloating(False)
        self.log_widget.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.log_widget.setAllowedAreas(Qt.BottomDockWidgetArea)
        self.log_layout = QWidget()
        self.log_layout.setObjectName(u"log_layout")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.log_layout.sizePolicy().hasHeightForWidth())
        self.log_layout.setSizePolicy(sizePolicy4)
        self.gridLayout_2 = QGridLayout(self.log_layout)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.log_content_layout = QVBoxLayout()
        self.log_content_layout.setObjectName(u"log_content_layout")
        self.log_content_layout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.log_text = QPlainTextEdit(self.log_layout)
        self.log_text.setObjectName(u"log_text")
        sizePolicy4.setHeightForWidth(self.log_text.sizePolicy().hasHeightForWidth())
        self.log_text.setSizePolicy(sizePolicy4)
        self.log_text.setMinimumSize(QSize(0, 0))
        self.log_text.setAcceptDrops(False)
        self.log_text.setFrameShape(QFrame.StyledPanel)
        self.log_text.setFrameShadow(QFrame.Sunken)
        self.log_text.setUndoRedoEnabled(False)
        self.log_text.setReadOnly(True)

        self.log_content_layout.addWidget(self.log_text)

        self.buttons_layout = QHBoxLayout()
        self.buttons_layout.setObjectName(u"buttons_layout")
        self.buttons_layout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.log_clear_button = QToolButton(self.log_layout)
        self.log_clear_button.setObjectName(u"log_clear_button")
        icon1 = QIcon()
        icon1.addFile(u"images/delete-sweep_24.png", QSize(), QIcon.Normal, QIcon.Off)
        self.log_clear_button.setIcon(icon1)
        self.log_clear_button.setIconSize(QSize(24, 24))

        self.buttons_layout.addWidget(self.log_clear_button)


        self.log_content_layout.addLayout(self.buttons_layout)


        self.gridLayout_2.addLayout(self.log_content_layout, 0, 0, 1, 1)

        self.log_widget.setWidget(self.log_layout)
        MainWindow.addDockWidget(Qt.BottomDockWidgetArea, self.log_widget)
        self.config_widget = QDockWidget(MainWindow)
        self.config_widget.setObjectName(u"config_widget")
        self.config_widget.setEnabled(True)
        self.config_widget.setMinimumSize(QSize(250, 600))
        self.config_widget.setFloating(False)
        self.config_widget.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.config_widget.setAllowedAreas(Qt.RightDockWidgetArea)
        self.config_layout = QWidget()
        self.config_layout.setObjectName(u"config_layout")
        self.gridLayout = QGridLayout(self.config_layout)
        self.gridLayout.setObjectName(u"gridLayout")
        self.config_content_layout = QFormLayout()
        self.config_content_layout.setObjectName(u"config_content_layout")

        self.gridLayout.addLayout(self.config_content_layout, 0, 0, 1, 1)

        self.config_widget.setWidget(self.config_layout)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.config_widget)
        self.plugins_widget = QDockWidget(MainWindow)
        self.plugins_widget.setObjectName(u"plugins_widget")
        self.plugins_widget.setMinimumSize(QSize(250, 600))
        self.plugins_widget.setAllowedAreas(Qt.LeftDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.plugins_widget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.plugins_widget)
        self.about_widget.raise_()
        self.log_widget.raise_()
        QWidget.setTabOrder(self.shuttle_tab, self.plug_button)
        QWidget.setTabOrder(self.plug_button, self.conf_button)
        QWidget.setTabOrder(self.conf_button, self.log_button)
        QWidget.setTabOrder(self.log_button, self.about_button)
        QWidget.setTabOrder(self.about_button, self.usb_status)
        QWidget.setTabOrder(self.usb_status, self.button_5)
        QWidget.setTabOrder(self.button_5, self.wheel_pos4)
        QWidget.setTabOrder(self.wheel_pos4, self.wheel_cent0)
        QWidget.setTabOrder(self.wheel_cent0, self.button_1)
        QWidget.setTabOrder(self.button_1, self.wheel_pos1)
        QWidget.setTabOrder(self.wheel_pos1, self.wheel_pos2)
        QWidget.setTabOrder(self.wheel_pos2, self.dial)
        QWidget.setTabOrder(self.dial, self.wheel_neg6)
        QWidget.setTabOrder(self.wheel_neg6, self.wheel_pos5)
        QWidget.setTabOrder(self.wheel_pos5, self.button_2)
        QWidget.setTabOrder(self.button_2, self.wheel_neg5)
        QWidget.setTabOrder(self.wheel_neg5, self.wheel_pos6)
        QWidget.setTabOrder(self.wheel_pos6, self.wheel_neg1)
        QWidget.setTabOrder(self.wheel_neg1, self.button_4)
        QWidget.setTabOrder(self.button_4, self.wheel_pos7)
        QWidget.setTabOrder(self.wheel_pos7, self.button_3)
        QWidget.setTabOrder(self.button_3, self.wheel_neg2)
        QWidget.setTabOrder(self.wheel_neg2, self.wheel_pos3)
        QWidget.setTabOrder(self.wheel_pos3, self.wheel_neg3)
        QWidget.setTabOrder(self.wheel_neg3, self.wheel_neg4)
        QWidget.setTabOrder(self.wheel_neg4, self.wheel_neg7)
        QWidget.setTabOrder(self.wheel_neg7, self.about_text)
        QWidget.setTabOrder(self.about_text, self.log_text)
        QWidget.setTabOrder(self.log_text, self.log_clear_button)
        QWidget.setTabOrder(self.log_clear_button, self.wheel_neg4_2)
        QWidget.setTabOrder(self.wheel_neg4_2, self.wheel_neg7_2)
        QWidget.setTabOrder(self.wheel_neg7_2, self.usb_status_2)
        QWidget.setTabOrder(self.usb_status_2, self.wheel_neg2_2)
        QWidget.setTabOrder(self.wheel_neg2_2, self.button_6)
        QWidget.setTabOrder(self.button_6, self.wheel_neg5_2)
        QWidget.setTabOrder(self.wheel_neg5_2, self.button_7)
        QWidget.setTabOrder(self.button_7, self.wheel_pos5_2)
        QWidget.setTabOrder(self.wheel_pos5_2, self.wheel_pos3_2)
        QWidget.setTabOrder(self.wheel_pos3_2, self.wheel_neg6_2)
        QWidget.setTabOrder(self.wheel_neg6_2, self.wheel_pos1_2)
        QWidget.setTabOrder(self.wheel_pos1_2, self.wheel_cent0_2)
        QWidget.setTabOrder(self.wheel_cent0_2, self.wheel_pos2_2)
        QWidget.setTabOrder(self.wheel_pos2_2, self.wheel_pos4_2)
        QWidget.setTabOrder(self.wheel_pos4_2, self.button_8)
        QWidget.setTabOrder(self.button_8, self.wheel_pos6_2)
        QWidget.setTabOrder(self.wheel_pos6_2, self.button_9)
        QWidget.setTabOrder(self.button_9, self.dial_2)
        QWidget.setTabOrder(self.dial_2, self.wheel_neg1_2)
        QWidget.setTabOrder(self.wheel_neg1_2, self.wheel_pos7_2)
        QWidget.setTabOrder(self.wheel_pos7_2, self.button_10)
        QWidget.setTabOrder(self.button_10, self.wheel_neg3_2)

        self.retranslateUi(MainWindow)

        self.shuttle_tab.setCurrentIndex(0)
        self.usb_status.setDefault(False)
        self.usb_status_2.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Open Contour Shuttle", None))
        self.action_Quit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
#if QT_CONFIG(tooltip)
        self.plug_button.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.plug_button.setStatusTip(QCoreApplication.translate("MainWindow", u"Configuration", None))
#endif // QT_CONFIG(statustip)
        self.plug_button.setText(QCoreApplication.translate("MainWindow", u"Plugins", None))
#if QT_CONFIG(tooltip)
        self.about_button.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.about_button.setStatusTip(QCoreApplication.translate("MainWindow", u"About", None))
#endif // QT_CONFIG(statustip)
        self.about_button.setText(QCoreApplication.translate("MainWindow", u"About", None))
#if QT_CONFIG(tooltip)
        self.conf_button.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.conf_button.setStatusTip(QCoreApplication.translate("MainWindow", u"Configuration", None))
#endif // QT_CONFIG(statustip)
        self.conf_button.setText(QCoreApplication.translate("MainWindow", u"Configuration", None))
#if QT_CONFIG(tooltip)
        self.log_button.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.log_button.setStatusTip(QCoreApplication.translate("MainWindow", u"Log", None))
#endif // QT_CONFIG(statustip)
        self.log_button.setText(QCoreApplication.translate("MainWindow", u"Log", None))
#if QT_CONFIG(accessibility)
        self.shuttle_tab.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.shuttle_widget.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(statustip)
        self.button_1.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 1", None))
#endif // QT_CONFIG(statustip)
        self.button_1.setText("")
#if QT_CONFIG(tooltip)
        self.usb_status.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.usb_status.setStatusTip(QCoreApplication.translate("MainWindow", u"USB connection status", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.usb_status.setWhatsThis(QCoreApplication.translate("MainWindow", u"USB Status", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(statustip)
        self.button_5.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 5", None))
#endif // QT_CONFIG(statustip)
        self.button_5.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos4.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 4", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos4.setText("")
#if QT_CONFIG(statustip)
        self.wheel_cent0.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: center", None))
#endif // QT_CONFIG(statustip)
        self.wheel_cent0.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos1.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 1", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos1.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 2", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos2.setText("")
#if QT_CONFIG(statustip)
        self.dial.setStatusTip(QCoreApplication.translate("MainWindow", u"Dial", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.wheel_neg6.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 6", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg6.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos5.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 5", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos5.setText("")
#if QT_CONFIG(statustip)
        self.button_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 2", None))
#endif // QT_CONFIG(statustip)
        self.button_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg5.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 5", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg5.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos6.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 6", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos6.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg1.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 1", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg1.setText("")
#if QT_CONFIG(statustip)
        self.button_4.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 4", None))
#endif // QT_CONFIG(statustip)
        self.button_4.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos7.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 7", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos7.setText("")
#if QT_CONFIG(statustip)
        self.button_3.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 3", None))
#endif // QT_CONFIG(statustip)
        self.button_3.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 2", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos3.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 3", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos3.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg3.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 3", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg3.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg4.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 4", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg4.setText(QCoreApplication.translate("MainWindow", u"-", None))
#if QT_CONFIG(statustip)
        self.wheel_neg7.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 7", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg7.setText("")
        self.shuttle_tab.setTabText(self.shuttle_tab.indexOf(self.shuttle_widget), QCoreApplication.translate("MainWindow", u"Xpress", None))
        self.shuttle_tab.setTabText(self.shuttle_tab.indexOf(self.shuttlepro_widget), QCoreApplication.translate("MainWindow", u"PRO", None))
#if QT_CONFIG(statustip)
        self.wheel_neg4_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 4", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg4_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
#if QT_CONFIG(statustip)
        self.wheel_neg7_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 7", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg7_2.setText("")
#if QT_CONFIG(tooltip)
        self.usb_status_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.usb_status_2.setStatusTip(QCoreApplication.translate("MainWindow", u"USB connection status", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.usb_status_2.setWhatsThis(QCoreApplication.translate("MainWindow", u"USB Status", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(statustip)
        self.wheel_neg2_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 2", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg2_2.setText("")
#if QT_CONFIG(statustip)
        self.button_6.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 2", None))
#endif // QT_CONFIG(statustip)
        self.button_6.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg5_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 5", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg5_2.setText("")
#if QT_CONFIG(statustip)
        self.button_7.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 3", None))
#endif // QT_CONFIG(statustip)
        self.button_7.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos5_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 5", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos5_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos3_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 3", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos3_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg6_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 6", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg6_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos1_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 1", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos1_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_cent0_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: center", None))
#endif // QT_CONFIG(statustip)
        self.wheel_cent0_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos2_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 2", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos2_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos4_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 4", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos4_2.setText("")
#if QT_CONFIG(statustip)
        self.button_8.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 4", None))
#endif // QT_CONFIG(statustip)
        self.button_8.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos6_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 6", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos6_2.setText("")
#if QT_CONFIG(statustip)
        self.button_9.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 1", None))
#endif // QT_CONFIG(statustip)
        self.button_9.setText("")
#if QT_CONFIG(statustip)
        self.dial_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Dial", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.wheel_neg1_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 1", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg1_2.setText("")
#if QT_CONFIG(statustip)
        self.wheel_pos7_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: right 7", None))
#endif // QT_CONFIG(statustip)
        self.wheel_pos7_2.setText("")
#if QT_CONFIG(statustip)
        self.button_10.setStatusTip(QCoreApplication.translate("MainWindow", u"Button 5", None))
#endif // QT_CONFIG(statustip)
        self.button_10.setText("")
#if QT_CONFIG(statustip)
        self.wheel_neg3_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Wheel position: left 3", None))
#endif // QT_CONFIG(statustip)
        self.wheel_neg3_2.setText("")
        self.shuttle_tab.setTabText(self.shuttle_tab.indexOf(self.shuttleprov2_widget), QCoreApplication.translate("MainWindow", u"PRO v2", None))
        self.about_widget.setWindowTitle(QCoreApplication.translate("MainWindow", u"About", None))
        self.about_text.setDocumentTitle("")
        self.log_widget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Log", None))
        self.log_clear_button.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.config_widget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Configuration", None))
        self.plugins_widget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Plugins", None))
    # retranslateUi

